local LSM = LibStub("LibSharedMedia-3.0")
local koKR, ruRU, zhCN, zhTW, western = LSM.LOCALE_BIT_koKR, LSM.LOCALE_BIT_ruRU, LSM.LOCALE_BIT_zhCN, LSM.LOCALE_BIT_zhTW, LSM.LOCALE_BIT_western

local MediaType_FONT = LSM.MediaType.FONT
local MediaType_STATUSBAR = LSM.MediaType.STATUSBAR

local MediaType_SOUND = LSM.MediaType.SOUND

LSM:Register(MediaType_FONT, "GothamNarrowUltra",       [[Interface\Addons\FDPUI\Game\Shared\Media\Fonts\GothamNarrowUltra.ttf]],                           ruRU + western)
LSM:Register(MediaType_FONT, "GothamNarrowUltra",       [[Interface\Addons\FDPUI\Game\Shared\Media\Fonts\GothamNarrowUltraAsia.ttf]],                       koKR + zhCN + zhTW)
LSM:Register(MediaType_FONT, "FDP",                   [[Interface\Addons\FDPUI\Game\Shared\Media\Fonts\FDP.ttf]],                                       ruRU + western)
LSM:Register(MediaType_FONT, "FDP",                   [[Interface\Addons\FDPUI\Game\Shared\Media\Fonts\FDPAsia.ttf]],                                   koKR + zhCN + zhTW)

LSM:Register(MediaType_STATUSBAR, "Melli",                  [[Interface\Addons\FDPUI\Game\Shared\Media\Textures\Melli]])
LSM:Register(MediaType_STATUSBAR, "FDPGradient",          [[Interface\Addons\FDPUI\Game\Shared\Media\Textures\FDPGradient]])
LSM:Register(MediaType_STATUSBAR, "FDPLeft",              [[Interface\Addons\FDPUI\Game\Shared\Media\Textures\FDPLeft]])
LSM:Register(MediaType_STATUSBAR, "FDPMouseover",         [[Interface\Addons\FDPUI\Game\Shared\Media\Textures\FDPMouseover]])
LSM:Register(MediaType_STATUSBAR, "FDPMouseoverArrows",   [[Interface\Addons\FDPUI\Game\Shared\Media\Textures\FDPMouseoverArrows]])
LSM:Register(MediaType_STATUSBAR, "FDPRight",             [[Interface\Addons\FDPUI\Game\Shared\Media\Textures\FDPRight]])
LSM:Register(MediaType_STATUSBAR, "FDPTarget",            [[Interface\Addons\FDPUI\Game\Shared\Media\Textures\FDPTarget]])

LSM:Register(MediaType_SOUND, "|cff0091ed1 -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\1.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed2 -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\2.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed3 -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\3.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed4 -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\4.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed5 -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\5.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed6 -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\6.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed7 -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\7.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed8 -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\8.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed9 -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\9.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed10 -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\10.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edAbsorb -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Absorb.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edAdd -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Add.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edAdds -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Adds.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edAoE -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\AoE.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edAvoid -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Avoid.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edBait -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Bait.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edBeam -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Beam.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edBehind -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Behind.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edBloodlust -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Bloodlust.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edBomb -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Bomb.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edBreath -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Breath.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edBuff -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Buff.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edCC -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\CC.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edCharge -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Charge.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edClear In -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\ClearIn.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edClear -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Clear.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edCollect -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Collect.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edCombat -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Combat.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edDance -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Dance.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edDebuff -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Debuff.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edDestroy -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Destroy.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edDispell -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Dispell.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edDodge Inc -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\DodgeInc.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edDodge -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Dodge.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edDot -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Dot.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edExternal -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\External.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edFixate -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Fixate.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edFreedom -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Freedom.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edFrontal -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Frontal.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edGreen -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Green.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edHide -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Hide.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edHigh Stacks -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\HighStacks.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edImmune -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Immune.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edIn -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\In.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edInc -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Inc.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edInside -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Inside.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edIntermission -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Intermission.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edKick -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Kick.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edKnock -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Knock.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edLeft -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Left.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edLinked -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Linked.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edLoS -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\LoS.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edMelee -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Melee.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edMount -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Mount.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edMove -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Move.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edNext -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Next.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edNuke -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Nuke.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edOrb -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Orb.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edOrbs -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Orbs.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edOut -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Out.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edOutrange -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Outrange.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edPersonal -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Personal.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edPot -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Pot.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edPull -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Pull.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edPush -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Push.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edRanged -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Ranged.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edReady -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Ready.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edRed -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Red.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edReflect -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Reflect.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edRight -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Right.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edRun -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Run.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edSac -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Sac.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edShield -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Shield.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edSoak -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Soak.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edSpike -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Spike.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edSpread -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Spread.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edStack -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Stack.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edStop -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Stop.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edStop Cast -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\StopCast.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edSwitch -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Switch.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edTaunt -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Taunt.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edTotem -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Totem.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edTrap -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Trap.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edTurn -FDP|r", [[Interface\Addons\FDPUI\Game\Shared\Media\Sounds\Turn.ogg]])
